'use strict';
require('../../');
var client = require('../../lib/JavaScriptStackTraceApi_client');
var getStackFrames_better = require('../../wip/getStackFrames_better');
var COUNT = 30000;
//var v8n = require('v8-natives');
//var v8p = require('v8-profiler');
//var fs = require('fs');

var x, i, startTime, endTime;
//v8p.startProfiling('captureStackTrace');
startTime = process.hrtime();
for (i = 0; i < COUNT; ++i) x = client.getStackFrames();
endTime = process.hrtime(startTime);
console.log(JSON.stringify(x.slice(4), null, "  "));
console.log(endTime);
//console.log("x=%d", x);
//var cpuProfile = v8p.stopProfiling('captureStackTrace');
//fs.writeFileSync('captureStackTrace.log', JSON.stringify(cpuProfile, null, "  "));
console.log('--------------------------------------');
//v8p.startProfiling('getStackParsedFrames');
startTime = process.hrtime();
for (i = 0; i < COUNT; ++i) x = client.getStackParsedFrames();
endTime = process.hrtime(startTime);
console.log(JSON.stringify(x.slice(4), null, "  "));
console.log(endTime);
//console.log("x=%d", x);
//var cpuProfile3 = v8p.stopProfiling('getStackParsedFrames');
//fs.writeFileSync('getStackParsedFrames.log', JSON.stringify(cpuProfile3, null, "  "));
console.log('--------------------------------------');
//v8p.startProfiling('getRawStackFrames');
startTime = process.hrtime();
for (i = 0; i < COUNT; ++i) x = getStackFrames_better();
console.log(JSON.stringify(x.slice(4), null, "  "));
endTime = process.hrtime(startTime);
console.log(endTime);
//var cpuProfile2 = v8p.stopProfiling('getRawStackFrames');
//fs.writeFileSync('getRawStackFrames.log', JSON.stringify(cpuProfile2, null, "  "));
